### ISSUE TITLE
Failed to bind mount: No machine 'debian' known

### ISSUE THREAD

**Issue by bluesiboy** [loaden/nspawn-qq#1]
我重启电脑运行`debian-qq`，遇到了一些错误。
![Screenshot_20210929_123758](https://user-images.githubusercontent.com/9855885/135204168-fa018f6e-11d2-41a3-97d7-3a0ee0cbb80f.png)

**Comment by loaden** [comment]
下载最新的2.2版本，执行：sudo ./debian-config.sh
