### ISSUE TITLE
Failed to bind mount: Failed to mount: No such file or directory

### ISSUE THREAD

**Issue by shey-kail** [loaden/nspawn-qq#2]
it works well, but when I run deepin-terminal it sees:
````
Connected to machine deepin. Press ^] three times within 1s to exit session.

Connection to machine deepin terminated.
Failed to bind mount: Failed to mount: No such file or directory
error: machinectl bind --read-only --mkdir deepin /run/user/1000/pulse
Failed to bind mount: Failed to mount: No such file or directory
Failed to bind mount: Failed to mount: No such file or directory
Failed to bind mount: Failed to mount: No such file or directory
error: machinectl bind --mkdir deepin /home/shey/Documents /home/u1000/Documents
Failed to bind mount: Failed to mount: No such file or directory
Failed to bind mount: Failed to mount: No such file or directory
Failed to bind mount: Failed to mount: No such file or directory
Failed to bind mount: Failed to mount: No such file or directory
Failed to bind mount: Failed to mount: No such file or directory
Failed to bind mount: Failed to mount: No such file or directory
Failed to bind mount: Failed to mount: No such file or directory
Failed to bind mount: Failed to mount: No such file or directory
Failed to bind mount: Failed to resolve source path: No such file or directory
Failed to bind mount: Failed to mount: No such file or directory
Failed to bind mount: Failed to mount: No such file or directory
error: machinectl bind --read-only --mkdir deepin /home/shey/.Xauthority /home/u1000/.Xauthority
non-network local connections being added to access control list
Connected to machine deepin. Press ^] three times within 1s to exit session.

** (lxterminal:391): WARNING **: 16:48:08.806: Bind on socket failed: permission denied
````
those don't affect the program i run itself, but the program can't read and write the host system's file.
Any way, thank you for providing nspawn-deepinwine project. such a good project that I love it when I got it

**Comment by bluesiboy** [comment]
get latest version, run `debian-config` or `deepin-config` command.
you can refer to details #1  with commit 03abee0f81b0b428d653daa6558fd3a0c67419a3.

**Comment by shey-kail** [comment]
> get latest version, run `debian-config` or `deepin-config` command. you can refer to details #1 with commit [03abee0](https://github.com/loaden/nspawn-deepinwine/commit/03abee0f81b0b428d653daa6558fd3a0c67419a3), it fixes startup item on reboot. or you can run `machinectl start debian` or `machinectl start deepin` to start it.

thank you for replying, I tried but it didn't work. I think the version of my systemd is too low.
I will tell you if I have new find

**Comment by shey-kail** [comment]
by the way, the folds, such as /home/shey/Downloads, are all available. Here is my environment:
system: debian 11
systemd version: 247.3-6

**Comment by loaden** [comment]
Thank you feedback this issue, it's sound like Debian 11's issue about systemd, we should talk about this on QQ group already.
If someone got this issue, may be follow the link here: https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1816433.html
