### ISSUE TITLE
升级了Linux5.15内核后，启动企业微信提示没装deepin容器，安装容器提示已存在

### ISSUE THREAD

**Issue by xiedonglin110** [loaden/nspawn-qq#3]
![image](https://user-images.githubusercontent.com/92143027/140699371-087f2bee-bf97-4378-9029-2663e6550092.png)
![image](https://user-images.githubusercontent.com/92143027/140699256-bed88abb-4083-4c07-811c-a6e2ea6627bc.png)
不知日志存放位置，故未能上传

**Comment by xiedonglin110** [comment]
![image](https://user-images.githubusercontent.com/92143027/140699406-d2f75a95-3852-449e-828e-b9f31b24885a.png)
上传了错误截图

**Comment by loaden** [comment]
请下载最新的master分支，或者3.3.1版本集成包，安装前执行：deepin-upgrade试试？我这里没问题。

**Comment by loaden** [comment]
![image](https://user-images.githubusercontent.com/490433/143668250-c1f22bb4-021f-47be-b783-8e47e2912b8e.png)
这是我从终端里安装的截图。如果还有问题，请提供宿主系统信息。
