### ISSUE TITLE
安装什么都不成功

### ISSUE THREAD

**Issue by bluesiboy** [loaden/nspawn-qq#5]
<font color=#FF0000 >这是我安装debian后安装qq的运行结果：</font>
![Screenshot_20211229_125616](https://user-images.githubusercontent.com/9855885/147827331-18047b39-5ddb-4bd4-8ded-b5e0d22ba74d.png)
<font color=#FF0000 >这些是我执行脚本的运行结果：</font>
![Screenshot_20211231_182246](https://user-images.githubusercontent.com/9855885/147827380-4304bb9c-bdbb-4eef-9fbd-de40c0da510e.png)
![Screenshot_20211231_182045](https://user-images.githubusercontent.com/9855885/147827393-0768be46-acfb-4751-be64-3698a48ce579.png)
<font color=#FF0000 >这是我测试machinectl的运行结果：</font>
![Screenshot_20211231_134328](https://user-images.githubusercontent.com/9855885/147827409-a5a72512-7e10-458f-a0e2-cebeb661d4ed.png)
<font color=#FF0000 >这是安装脚本中发现的异常：</font>
![Screenshot_20211231_133431](https://user-images.githubusercontent.com/9855885/147827424-8da61bdd-0b1d-4c09-86a9-ae680c343b8b.png)
![image](https://user-images.githubusercontent.com/9855885/147827736-e506e8e6-b8a8-4805-a4b3-2b33c5991152.png)
<font color=#FF0000 >这是我根据提示尝试解决未果：</font>
![Screenshot_20211231_134111](https://user-images.githubusercontent.com/9855885/147827416-a2fb4fef-c7bf-41d5-8ccf-9d5ee45a9a56.png)

**Comment by loaden** [comment]
请问你电脑是不是N卡？

**Comment by bluesiboy** [comment]
> 请问你电脑是不是N卡？

不是N卡，是A卡。
在基于ext4得Manjaro上安装成功运行了，在Arch上也遇到了错误，然后用QQ群里的安装包也成了。
可是在基于btrfs的Arch上就遇到了现在这个错误。（Home文件夹我挂载的是上个Arch的Home文件夹（这个也是新安装的没怎么用，然后听说了btrfs后立马重做了系统））

**Comment by loaden** [comment]
我最近测试了基于Btrfs的Arch（Garuda），也是你一样的问题，没找到原因。

**Comment by bluesiboy** [comment]
> 我最近测试了基于Btrfs的Arch（Garuda），也是你一样的问题，没找到原因。

我试试将debian文件夹移出btrfs文件系统能不能运行，请问就这两个关键文件夹吧？

**Comment by loaden** [comment]
感觉和btrfs文件系统应该没有关系，之前我一直用的btrfs文件系统测试的。
出问题的一般都是滚动更新版本，所以可能与内核或者systemd自身的bug有关。
但我找不到原因。

**Comment by loaden** [comment]
我觉得systemd版本自身bug的可能性最大。我准备在Gentoo上降级systemd试试。

**Comment by loaden** [comment]
在Fedora 35上测试，systemd 249.7容器运行QQ一切正常，升级系统后，systemd版本变成249.9，然后容器QQ就无法运行了。确定是systemd的bug。

**Comment by bluesiboy** [comment]
> 在Fedora 35上测试，systemd 249.7容器运行QQ一切正常，升级系统后，systemd版本变成249.9，然后容器QQ就无法运行了。确定是systemd的bug。

我可不可以找人要个正常的文件放到出问题的电脑上继续运行？？？
应该怎么做才能去尝试我这个想法呢？

**Comment by loaden** [comment]
我尝试一下创建Arch的容器，目前发现Debian 11是可以运行的。也就是说，问题的根源，是容器内外的systemd版本差距过大导致的。起码，Debian 11用的systemd 247是可以在我host 249.9的Gentoo上正常工作的。

**Comment by bluesiboy** [comment]
> 

确实，好了。
