### ISSUE TITLE
运行软件都失败

### ISSUE THREAD

**Issue by Huang-Yujiong** [loaden/nspawn-qq#8]
执行完sudo ./nas...deepin.sh 的脚本后 安装软件  执行  报错如下。提示没有用户，找不到文件夹。

```bash
HOST_HOME=/home/hyj
HOST_USER=hyj
USER_UID=1000
Connected to machine deepin. Press ^] three times within 1s to exit session.
'/home/hyj' -> '/home/u1000'
Connection to machine deepin terminated.
**Failed to bind mount: Failed to mount: No such file or directory**
error: machinectl bind --read-only deepin /run/user/1000/gdm/Xauthority /home/u1000/.Xauthority
non-network local connections being added to access control list
Connected to machine deepin. Press ^] three times within 1s to exit session.
su: user u1000 does not exist
Connection to machine deepin terminated.
```

系统是Ubuntu20.04  
容器安装的是deepin   

目前已经尝试过升级deepin 系统 ， 按照readme 的命令update updrade都尝试了 还是不行。  
除此之外，尝试了高级功能， 登入用户---无法登入u1000 用户。

以上.............

1 . 另外想问问应该怎么做此次安装删除干净--我目前已经删除了软件。

**Comment by Huang-Yujiong** [comment]
之前安装的是deepin 的，我又接着执行了debian 的脚本 安装debian 。 安装过程中报错信息如下， 也是显示用户不存在 



LC_MEASUREMENT=zh_CN.UTF-8
LC_IDENTIFICATION=zh_CN.UTF-8
LC_ALL=
useradd：无效的 shell“bash”
chpasswd: (user u1000) pam_chauthtok() failed, error:
鉴定令牌操作错误
chpasswd：(第 1 行，用户 u1000) 不存在
/config.sh: line 30: cd: /home/u1000/: No such file or directory
chown: 无效的用户: “u1000:u1000”
useradd：无效的 shell“bash”
chpasswd: (user u1001) pam_chauthtok() failed, error:
鉴定令牌操作错误
chpasswd：(第 1 行，用户 u1001) 不存在
/config.sh: line 30: cd: /home/u1001/: No such f

**Comment by Huang-Yujiong** [comment]
```bash
~/Software/nspawn-deepinwine$ debian-qq
HOST_HOME=/home/hyj
HOST_USER=hyj
USER_UID=1000
Connected to machine debian. Press ^] three times within 1s to exit session.
'/home/hyj' -> '/home/u1000'
Connection to machine debian terminated.
Failed to bind mount: Failed to mount: No such file or directory
error: machinectl bind --read-only debian /run/user/1000/gdm/Xauthority /home/u1000/.Xauthority
non-network local connections being added to access control list
Connected to machine debian. Press ^] three times within 1s to exit session.
su: user u1000 does not exist
Connection to machine debian terminated.
```

在安装完Debian后 再次尝试运行qq  也是报出 相同的错误  
如上

**Comment by loaden** [comment]
嗯，误删了创建用户的/bin/bash，导致创建用户失败了。已经修复。
