### ISSUE TITLE
建议换一下容器里面的默认镜像源

### ISSUE THREAD

**Issue by SzLeaves** [loaden/nspawn-qq#9]
现在容器里面的清华源其实速度并不快了（很多时候会断连）
可以切换到他们的另外一个站点（北外镜像源）：https://mirrors.bfsu.edu.cn/debian/

**Comment by loaden** [comment]
https://github.com/loaden/nspawn-qq/commit/58356370d43a4c904da735f2185f96e60ab24475
已更换
